// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC0824xBNgfg8Bc55T8kdolaZKRD8jW94',
    appId: '1:662598143151:android:12030c7b3d4fc63614985a',
    messagingSenderId: '662598143151',
    projectId: 'flew-travel-app',
    databaseURL: 'https://flew-travel-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flew-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir1zlu9G1Bpmbsgjnjl0EL9UGva6XwJ0',
    appId: '1:662598143151:ios:19042b1fc6471f9814985a',
    messagingSenderId: '662598143151',
    projectId: 'flew-travel-app',
    databaseURL: 'https://flew-travel-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flew-travel-app.appspot.com',
    iosClientId: '662598143151-s1j7r1h71oeeikjtoeha0i8c5ue7hq02.apps.googleusercontent.com',
    iosBundleId: 'com.example.flewTravel',
  );
}
